Repository 7T4-DevPlus/Client_OJT7T4, pull requests merged in 2023-12, with the labels that each got.

#1 create context and reducer for employee
  package-lock.json
  package.json
  src/App.js
  src/contexts/constants.js
  src/contexts/employeeContext.js
  src/reducers/employeeReducer.js
Labels: documentation, enhancement

#2 create technical context and reducer
  src/App.js
  src/contexts/employeeContext.js
  src/contexts/technicalContext.js
  src/reducers/technicalReducer.js
Labels: documentation, enhancement

#4 Create components in input to reuse them later.
  src/App.js
  src/components/ButtonCommon.jsx
  src/components/CheckBoxCommon.jsx
  src/components/DateCommon.jsx
  src/components/InputPassWord.jsx
  src/components/InputTextCommon.jsx
  src/components/RadioCommon.jsx
  src/contexts/componentsContext.js
  src/contexts/constants.js
  src/pages/employee/addEmployee.js
Labels: documentation, enhancement

#5 create button components
  src/components/CheckBoxCommon.jsx
  src/components/RadioCommon.jsx
Labels: documentation, enhancement

#7 Confirm modal
  src/App.js
  src/components/Dialog.jsx
Labels: documentation, enhancement

#12 Feature emptw7 11/employees page
  package-lock.json
  package.json
  src/App.js
  src/components/Modal/ConfirmModal.jsx
  src/components/buttons/ButtonCommon.jsx
  src/components/employee/addEmployeeModal.jsx
  src/components/employee/employeeForm.jsx
  src/components/inputs/CheckBoxCommon.jsx
  src/components/inputs/DateCommon.jsx
  src/components/inputs/InputPassWord.jsx
  src/components/inputs/InputTextCommon.jsx
  src/components/inputs/RadioCommon.jsx
  src/contexts/componentsContext.jsx
  src/contexts/constants.jsx
  src/contexts/employeeContext.jsx
  src/contexts/technicalContext.jsx
  src/pages/employee/employeeDetails.jsx
  src/pages/employee/employees.jsx
  src/reducers/employeeReducer.jsx
  src/reducers/technicalReducer.jsx
Labels: documentation, enhancement

#14 create project and role context provider
  src/App.jsx
  src/contexts/projectContext.jsx
  src/contexts/roleContext.jsx
  src/contexts/technicalContext.jsx
  src/pages/project/projectDetails.jsx
  src/pages/project/projects.jsx
  src/reducers/projectReducer.jsx
  src/reducers/roleReducer.jsx
Labels: documentation, enhancement

#16 create auth context
  src/App.jsx
  src/contexts/authContext.jsx
  src/contexts/constants.jsx
  src/reducers/authReducer.jsx
  src/utils/setAuthToken.jsx
Labels: documentation, enhancement

#15 add employee histories to employee details page
  package-lock.json
  package.json
  src/components/buttons/ButtonCommon.jsx
  src/components/employee/employeeForm.jsx
  src/components/employee/employeeHistory.jsx
  src/components/employee/historyCard.jsx
  src/contexts/employeeContext.jsx
  src/pages/employee/employeeDetails.jsx
  src/pages/employee/employees.jsx
  src/reducers/employeeReducer.jsx
Labels: documentation, enhancement

#20 Refactor/employee page
  src/JsonData/CountryCodes.json
  src/components/alerts/alertCommon.jsx
  src/components/buttons/ButtonCommon.jsx
  src/components/buttons/ButtonComponent.css
  src/components/employee/addEmployeeModal.jsx
  src/components/employee/employeeForm.jsx
  src/components/inputs/CheckBoxCommon.jsx
  src/components/layout/SideBar.jsx
  src/contexts/employeeContext.jsx
  src/pages/employee/employeeDetails.jsx
  src/pages/employee/employees.jsx
Labels: documentation, duplicate

#19 record page, change sidebar, search box and search by name functionn
  package-lock.json
  package.json
  src/App.jsx
  src/components/layout/Layout.jsx
  src/components/layout/NavBar.jsx
  src/components/layout/SideBar.jsx
  src/components/layout/searchBox.jsx
  src/contexts/constants.jsx
  src/contexts/employeeContext.jsx
  src/contexts/recordlogContext.jsx
  src/pages/employee/employees.jsx
  src/pages/log/logPage.jsx
  src/reducers/recordReducer.jsx
Labels: documentation, enhancement

#21 create add employee to project modal
  package-lock.json
  package.json
  src/components/employee/assignEmployeeModal.jsx
  src/components/employee/employeeInProject.jsx
  src/components/employee/employeeInProjectModal.jsx
  src/contexts/projectContext.jsx
  src/pages/project/projectDetails.jsx
Labels: documentation, duplicate, enhancement

#23 This is code CSS Task emptw7 60/login page
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/Router/PrivateRoute.jsx
  src/Router/routes.js
  src/filters/isLogin.js
  src/index.js
  src/pages/login/loginPage.jsx
  src/pages/login/loginStyle.css
Labels: documentation, duplicate

#33 Fixbug
  src/components/buttons/ButtonCommon.jsx
  src/components/buttons/ButtonComponent.css
  src/components/employee/addEmployeeModal.jsx
  src/components/employee/employeeForm.jsx
  src/components/employee/historyCard.jsx
  src/components/layout/searchBox.jsx
  src/components/project/assignEmployeeModal.jsx
  src/components/project/employeeInProject.jsx
  src/components/project/projectCard.jsx
  src/components/project/projectForm.jsx
  src/contexts/componentsContext.jsx
  src/contexts/employeeContext.jsx
  src/contexts/projectContext.jsx
  src/pages/employee/employees.jsx
  src/pages/log/logPage.jsx
  src/pages/login/loginPage.jsx
  src/pages/project/projectDetails.jsx
  src/pages/project/projects.jsx
  src/reducers/projectReducer.jsx
Labels: documentation

#34 Finish dashboard of the page
  package-lock.json
  package.json
  src/App.css
  src/pages/dashboard/Dashboard.jsx
Labels: documentation, enhancement
